### ISSUE TITLE
Storage.getAllKeys throwing an error on normal-looking use case

### ISSUE THREAD

**Issue by jlmurphysa** [echowaves/expo-storage#6]
Hi. I need some help, please!

I'm calling this method (should be very standard and return all keys in the storage), but it throws an error:
```
import Storage from 'expo-storage'
...
  static async getAllKeys(): Promise<string[]> {
    console.log('calling Storage.getAllKeys')
    try {
      const allKeys = await Storage.getAllKeys()
      console.log('allKeys :>> ', allKeys)
      return allKeys
    } catch (e) {
      console.log('e :>> ', e)
      return []
    }
  }
  ```
  
  Console output:
  ```
 LOG  calling Storage.getAllKeys
 LOG  e :>>  [Error: Received 2 arguments, but 1 was expected]
  ```

All the other Storage methods are working great with my app already, and are implemented in the same class using static methods, but this one is a bit of an issue.
What am I doing wrong?

**Comment by dmitryame** [comment]
Hmmm,
should work.
are you sure it fails on the await Storage.getAllKeys(), and not on the line that follows after that -- the console.log?
Are you sure you are using string values as keys? Can you
console.log(allKeys.toString())
or something

**Comment by jlmurphysa** [comment]
Really don't know. Couldn't figure it out, so just swapped out the library for:
 https://www.npmjs.com/package/@react-native-async-storage/async-storage
 
 ... which has a very similar API and worked 100% without any modification.

Thanks a lot for the quick response. 

Feel free to close, since it may be something specific to my configuration (although I can't think what that would be).  If the issue hasn't been reported before, I doubt its happening typically.
